services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - SSL_MODE=off
      - PHP_OPCACHE_ENABLE=0
    ports:
      - 80:8080
      # - 443:8443 # SSL_MODE
      - 5173:5173
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upn-news
    ports:
      - '3307:3306'

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8081:80'
    depends_on:
      - mysql

  mailpit:
    image: axllent/mailpit
    ports:
      - '8025:8025' # Panel
      - '1025:1025' # SMTP

volumes:
  mysql-data:
  redis-data:
